name: odyssey
#on:
#  push:
#    branches:
#      - master
#    paths:
#      - .github/workflows/odyssey.yaml
#      - Dockerfile
on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag
        required: true

jobs:
  setup-build-publish-deploy:
    name: Build Odyssey
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

          # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
#          platforms: linux/amd64,linux/arm/v7
          platforms: linux/amd64
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/odyssey:${{ github.event.inputs.tag }},${{ secrets.DOCKERHUB_USERNAME }}/odyssey:latest"
